services:
    scraper:
        build:
            dockerfile: Dockerfile
            context: .
        image: env-finder:1.0
        ports:
            - "6767:6767"
        volumes:
            - ./data:/app/data
            - ./logs:/app/logs
        env_file:
            - .env